---
title: 'Tidy Tuesday 2022/03/24'
author: "Lisa Lendway"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
# You may want to comment this out at first so you see important messages and warnings
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting themes
library(ggtext)        # for adding color to titles
library(gganimate)     # for animation
theme_set(theme_minimal())       # My favorite ggplot() theme :)
```

The data this week are about baby names!. Read more details [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-03-22/readme.md). 

```{r}
# Read in the data for the week
babynames <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-22/babynames.csv')


```


## within 30 minute

```{r}
name_of_interest <- "Cori"

babynames %>% 
  filter(name == name_of_interest) %>% 
  ggplot(aes(x = year,
             y = n,
             color = sex)) +
  geom_line() +
  labs(title = paste0("The number of people with the name ",
                      name_of_interest))
```


```{r}
name_of_interest <- "Cori"

babynames %>% 
  filter(name == name_of_interest) %>% 
  ggplot(aes(x = year,
             y = n,
             color = sex)) +
  geom_line() +
  scale_x_continuous(breaks = seq(1880, 2020, 10)) +
  labs(title = paste0("The number of people with the name ",
                      name_of_interest))
```

```{r}
the_chrises <-
  babynames %>% 
  filter(str_starts(name, "Chris")) %>% 
  group_by(sex, name) %>% 
  summarize(total_n = sum(n)) %>% 
  slice_max(order_by = total_n, n = 5)

chris_plot <-
babynames %>% 
  semi_join(the_chrises,
            by = c("sex", "name")) %>% 
  group_by(sex) %>% 
  ggplot(aes(x = year,
             y = n,
             group = name,
             color = sex)) +
  geom_line() +
  geom_vline(data = . %>% 
               group_by(sex, name) %>% 
               slice_max(order_by = n, n = 1),
             aes(xintercept = year, 
                 color = sex),
             linetype = 3) +
  geom_text(data = . %>% 
               group_by(sex, name) %>% 
               slice_max(order_by = n, n = 1),
             aes(x = 1890, 
                 y = n*.9,
                 color = sex,
                 label = year)) +  
  facet_wrap(vars(sex, fct_reorder(name, n, sum, .desc = TRUE)),
             scales = "free_y",
             ncol = 2, 
             dir = "v", 
             strip.position = "right") +
  scale_x_continuous(breaks = seq(1880, 2020, 20)) +
  scale_y_continuous(labels = scales::comma) +
  labs(title = "The number of people with the most popular names that start with Chris",
       subtitle = "Year indicates the most popular year with that name",
       x = "",
       y = NULL) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(), 
        axis.text = element_text(size = 8),
        legend.position = "none",
        plot.title.position = "plot")

chris_plot
```
```{r, eval=FALSE}
ggsave("images/babynames.png",
       chris_plot, 
       width = 6.5,
       height = 6.5, 
       units = "in")
```

## After 30

